/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TSPChartFrame.java
 *
 * Created on 22-jun-2011, 9:07:52
 */
package IA.TSP2;

import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author bejar
 */
public class TSPChartFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private final XYSeries data;

    /** Creates new form TSPChartFrame
     * @param data 
     */
    public TSPChartFrame(XYSeries data,String leg) {
        initComponents();
        this.data = data;

        // Add the series to your data set
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(data);
// Generate the graph
        JFreeChart chart = ChartFactory.createXYLineChart(
                "Evolucion del coste ("+leg+")",
                // Title
                "pasos",
                // x-axis Label
                "coste",
                // y-axis Label
                dataset,
                // Dataset
                PlotOrientation.VERTICAL, // Plot Orientation
                true,
                // Show Legend
                true,
                // Use tooltips
                false);
        ChartPanel localChartPanel = new ChartPanel(chart, true, true, true, true, true);
        localChartPanel.setPreferredSize(new Dimension(800, 400));
        localChartPanel.setVisible(true);
        add(localChartPanel);
        localChartPanel.setBounds(0, 0, 800, 400);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbCerrar.setText("Cerrar");
        jbCerrar.setName("jbCerrar"); // NOI18N
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(jbCerrar)
                .addGap(350, 350, 350))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addComponent(jbCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TSPChartFrame(null,null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCerrar;
    // End of variables declaration//GEN-END:variables
}
